
<div id="mainContent"><?php include TEMPLATE.DIRECTORY_SEPARATOR.'homepage.html'?></div>
<script>
   function onSignIn(googleUser) {
        var idToken=googleUser.getAuthResponse().id_token;
        $.post("/google_login/verify_id_token",{"id_token":idToken},function(data){
            console.log(data);
       });
   }
</script>
<script>
$("#searchInput").keyup(function (e) {
    if(e.keyCode==13) {
        window.location.href = "/prop/l/"+$(this).val();
    }
});

</script>