<?php $vdata=$this->view_data; ?>
<html>
<head>
    <title><?php echo $vdata["title"]?></title>
    <?php
    if(isset($vdata["scripts"])) {
        foreach ($vdata["scripts"] as $script) {
            if(file_exists("js" .DIRECTORY_SEPARATOR. $script )) {
                echo "<script src='/js" . DIRECTORY_SEPARATOR . $script . "'></script>";
            }
        }
    }
    if(isset($vdata["stylesheets"])) {
        foreach ($vdata["stylesheets"] as $stylesheet) {
            if(file_exists("css" .DIRECTORY_SEPARATOR. $stylesheet )) {
                echo "<link href='/css" . DIRECTORY_SEPARATOR . $stylesheet . "' rel='stylesheet'>";
            }
        }
    }
    ?>
</head>
<body>
<?php
if(isset($vdata["navbar"])){
    $navpath=TEMPLATE."navbars".DIRECTORY_SEPARATOR;
    if(file_exists($navpath.$vdata["navbar"])){
        include $navpath.$vdata["navbar"];
    }else{
        include $navpath.'navbar.html';

    }
}

?>


