<!DOCTYPE html>
<?php
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
$vdata=$this->view_data;

$custom_templates=array("inputs/toggleInput.html");
?>
<html>
<head>

    <title><?php echo $vdata["title"]?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--    loading custom templates-->
    <?php
        foreach ($custom_templates as $template){
            include TEMPLATE.$template;
        }
    ?>

    <script src="https://apis.google.com/js/client:platform.js?onload=start" async defer></script>
    <script>
        function start() {
            gapi.load('auth2', function() {
                auth2 = gapi.auth2.init({
                    client_id: '316686701656-1cs0k0pc8kpfihuirpetvltlrlp0nb9j.apps.googleusercontent.com',
                });
            });
            gapi.signin2.render("signin-button",{
                'longtitle': true,
                'theme': 'dark'
            });

        }
    </script>
    <link href="https://fonts.googleapis.com/css2?family=Alegreya&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400&display=swap" rel="stylesheet">
    <?php

    //    Dynamically loaded scripts from viewdata
    if(isset($vdata["scripts"])) {
        foreach ($vdata["scripts"] as $script) {
            if(is_array($script)){
                foreach ($script as $sc){
                    if(file_exists("js" .DIRECTORY_SEPARATOR. $sc )) {
                        echo "<script src='/js" . DIRECTORY_SEPARATOR . $sc . "'></script>";
                    }else{
                        echo "<script src='".$sc."'></script>";
                    }
                }
            }else{
                if(file_exists("js" .DIRECTORY_SEPARATOR. $script )) {
                    echo "<script src='/js" . DIRECTORY_SEPARATOR . $script . "'></script>";
                }else{
                    echo "<script src='".$script."'></script>";
                }}
        }
    }

//    Dynamically loaded stylesheets from viewdata
    if(isset($vdata["stylesheets"])) {
        foreach ($vdata["stylesheets"] as $stylesheet) {
            if(is_array($stylesheet)) {
                foreach ($stylesheet as $st) {
                    if (file_exists("css" . DIRECTORY_SEPARATOR . $st)) {
                        echo "<link href='/css" . DIRECTORY_SEPARATOR . $st . "' rel='stylesheet'>";
                    } else {
                        echo "<link href='" . $st . "' rel='stylesheet'>";
                    }
                }
            }else{
                    if (file_exists("css" . DIRECTORY_SEPARATOR . $stylesheet)) {
                        echo "<link href='/css" . DIRECTORY_SEPARATOR . $stylesheet . "' rel='stylesheet'>";
                    } else {
                        echo "<link href='" . $stylesheet . "' rel='stylesheet'>";

                    }
                }

        }
    }


    ?>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />


</head>
<body>
<div id="login-modal" style="display: none" class="modal">
    <?php include TEMPLATE.DIRECTORY_SEPARATOR.'login'.DIRECTORY_SEPARATOR."loginmodal.html";?>
</div>
<div id="login-info-modal" style="display: none" class="modal">
    <?php include TEMPLATE.DIRECTORY_SEPARATOR.'login'.DIRECTORY_SEPARATOR."logininfomodal.html";?>
</div>
<?php
if(isset($vdata["navbar"])){
    $navpath=TEMPLATE."navbars".DIRECTORY_SEPARATOR;
    if(file_exists($navpath.$vdata["navbar"])){
        include $navpath.$vdata["navbar"];
    }else{
        include $navpath.'navbar.html';
    }
}

?>



