<?php $vdata=$this->view_data; ?>
<html>
<head>
    <title><?php echo $vdata["title"]?></title>
    <meta name="google-signin-client_id" content="316686701656-1cs0k0pc8kpfihuirpetvltlrlp0nb9j.apps.googleusercontent.com">

    <script src="https://apis.google.com/js/client:platform.js" async defer></script>
    <?php
    if(isset($vdata["scripts"])) {
        foreach ($vdata["scripts"] as $script) {
            if(file_exists("js" .DIRECTORY_SEPARATOR. $script )) {
                echo "<script src='/js" . DIRECTORY_SEPARATOR . $script . "'></script>";
            }
        }
    }
    if(isset($vdata["stylesheets"])) {
        foreach ($vdata["stylesheets"] as $stylesheet) {
            if(file_exists("css" .DIRECTORY_SEPARATOR. $stylesheet )) {
                echo "<link href='/css" . DIRECTORY_SEPARATOR . $stylesheet . "' rel='stylesheet'>";
            }
        }
    }
    ?>
<!--    <script>-->
<!--        function start() {-->
<!--            gapi.load('auth2', function() {-->
<!--                auth2 = gapi.auth2.init({-->
<!--                    client_id: '316686701656-1cs0k0pc8kpfihuirpetvltlrlp0nb9j.apps.googleusercontent.com',-->
<!--                    // Scopes to request in addition to 'profile' and 'email'-->
<!--                    //scope: 'additional_scope'-->
<!--                });-->
<!--            });-->
<!--        }-->
<!--    </script>-->
</head>
<body>
<?php
if(isset($vdata["navbar"])){
    $navpath=TEMPLATE."navbars".DIRECTORY_SEPARATOR;
    if(file_exists($navpath.$vdata["navbar"])){
        include $navpath.$vdata["navbar"];
    }else{
        include $navpath.'navbar.html';
    }
}

?>


