<?php
$allprops=$this->view_data["data"];

$location=$this->view_data["location"];
?>
<div class="rowflex" id="listprops-heading-bar">
    <button class="fontAwesomeBTN" id="show-prop-filters"><i class="fa fa-bars" ></i></button>
    <h1 class="heading">Properties in <?php echo $location?></h1>
</div>

<div class="rowflex">

<!--    Div for filter box-->
    <div id="filter-searched-props" class="animationMenu" status="close">
<!--        Div for padding-->
        <div>
            <h1>Filter</h1>
            <div id="priceFilter">
                <h3>Price</h3>
                <input type="range">
            </div>
            <div id="ratingFilter">
                <h3>Rating</h3>
                <input type="range">

            </div>
            <div id="genderFilter">
                <h3>Gender</h3>
                <input type="radio" name="gender" value="Male" id="male">
                <label for="male">Male</label><br>
                <input type="radio" name="gender" value="Female" id="female">
                <label for="male">Female</label><br>
                <input type="radio" name="gender" value="Other" id="other">
                <label for="male">Other</label><br>

            </div>
        </div>
    </div>

<!--    Div showing all properties in a grid-->
    <div class="listprops-grid">
        <?php foreach ($allprops as $prop):
            $prop_title="/prop/v/".str_replace(' ','-',$prop["title"])."/".$prop["id"];
            $images=explode(",",$prop["images"]);
            $i=1;
            $wishlisted=false;
            if(isset($prop["wishlisted"])){
                $wishlisted=$prop["wishlisted"];
            }
        ?>
    <!--            echo "<a href='/prop/v/".$prop_title ."/".$prop["id"]."'>".$prop["title"]."</a><br>";-->
                <div class="listprops-item" src=<?php echo $prop_title; ?>>
                    <div class="img-overlay initial">

<!--                        Description button with bars at top left-->
                        <button class="fontAwesomeBTN show-desc-btn" ><i class="fa fa-bars"></i> </button>

<!--                        Prev img nav button-->
                        <button class="fontAwesomeBTN img-prev"><i class="fa fa-chevron-left "></i></button>

<!--                        Next img nav button-->

                        <button class="fontAwesomeBTN img-next" yo="fds"><i class="fa fa-chevron-right"></i></button>

<!--                        Add to wishlist button-->
                        <button class="add-to-wishlist-btn" wishlist="<?php echo $wishlisted ?>" for="<?php echo $prop['id'];?>"><i class="fa fa-heart"></i> </button>

<!--                       Area to show description , initially hidden-->
                        <div class="show-desc-area" style="display: none">
                            <p><?php echo $prop["description"] ?></p>
                        </div>



                        <?php foreach ($images as $img): ?>
                        <img num="<?php echo $i?>" src="<?php echo "/uploads/".$img ?>">
                        <?php $i++; endforeach; ?>
                        <input type="hidden" class="numOfImgs" value="<?php echo count($images) ?>">
                        <div class="bottom-circles">
                            <?php for($i=0;$i<count($images);$i++): ?>
                                <button class="fontAwesomeBTN img-circles"><i class="fa fa-circle"></i></button>

                            <?php endfor;?>

                        </div>

                    </div>
                    <div id="prop-title-box" >
                        <p id="prop-title"><?php echo $prop["title"] ?></p>
                        <p id="prop-address"><?php echo $prop["address"] ." , " .$prop["city"] ?></p>
                    </div>
                    <div>
                    <div class="star-rating-box">
                        <div class="back-stars">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                            <div class="front-stars" stars="4.1" total="5">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                        </div>
                        <p>4.1(30)</p>
                    </div>
                    </div>
                </div>
         <?php endforeach;?>

    </div>
</div>
<script>
    $(document).ready(function() {
        $(".listprops-item").click(function () {
            // check if img prev and next buttons are not clicked
            var check1=$(this).find(".img-next").prop("disabled");
            var check2=$(this).find(".img-prev").prop("disabled");

           if(check1==false && check2==false)
                window.location.href = $(this).attr("src");
        });

        // to prevent window to scroll when div is scrolling
        $( '.show-desc-area' ).on( 'mousewheel DOMMouseScroll', function ( e ) {
            var e0 = e.originalEvent,
                delta = e0.wheelDelta || -e0.detail;

            this.scrollTop += ( delta < 0 ? 1 : -1 ) * 8;
            e.preventDefault();
        });

        $(".show-desc-btn").on("click",function (e) {
            var descArea=$(this).siblings(".show-desc-area");
            if(descArea.css("display") == "none") {
                descArea.fadeIn(300);
            }else{
                descArea.fadeOut(300);

            }
            e.stopPropagation();
        });
        $(".img-overlay img[num='1']").addClass("active");

    });
</script>