<?php
$allprops=$this->view_data["data"];

$location=$this->view_data["location"];
$search=$this->view_data["search"];
$filters=$this->view_data["filters"];
?>
<div id="single-listing" class="template">
    <?php require TEMPLATE . "listing" . DIRECTORY_SEPARATOR . "single-listing.html" ?>
</div>
<script>
    <?php
    echo "var props = ".json_encode($allprops) . ";\n";
    echo "var filters= ".json_encode($filters).";\n";
    ?>
</script>
<div id="listprops-main-box">
    <div class="rowflex" id="listprops-heading-bar">
        <button class="fontAwesomeBTN" id="show-prop-filters"><i class="fa fa-bars" ></i></button>
        <h1 class="heading">Properties in <?php echo $location?></h1>
    </div>

    <div  >

    <!--    Div for filter box-->
        <div id="filter-searched-props" class="animationMenu" status="open">
<?php
$filter_action="/prop/l/".$location;
if($search!="")
    $filter_action.=("/".$search)


  ?>
            <form action="<?php echo $filter_action ?>" method="get" id="filter-props-form" class="rowflex">

        <!--               PRICE FILTER SECTION-->
                <div id="priceFilter" class="filter-divs">
<!--                    filter-btn class for every filter button-->
                    <button type="button" style="margin-left: 0px" class="text-icon filter-btn" id="filter-price-btn">Price Range</button>
                    <div class="filter-box raised-box toggleVisible " visible="false">
                        <p class="text-icon">Apply price filter</p>
                        <div id="price-filter-slider"></div>
                        <div class="rowflex" style="margin-top: 1em">
                            <div class="price-inputs">
                                <label for="minPrice">min price</label><br>
                                <span>&#8377;</span>
                                <input type="number" class="price-inputs" value="0" id="minPrice" name="minPrice">
                            </div>
                            <i class="fa fa-minus" style="align-self: center"></i>
                            <div class="price-inputs">
                                <label for="minPrice">max price</label><br>
                                <span>&#8377;</span>
                                <input type="number" class="price-inputs" value="0" id="maxPrice" name="maxPrice">
                            </div>
                            </div>
                        <div id="price-filter-submitbtns" class="filter-submit-btns">
                            <input class="text-small-icon" type="button" value="Clear">
                            <input class="text-small-icon" type="submit" value="Apply">
                        </div>
                        </div>
                    </div>

                <!--               PROP TYPE FILTER SECTION-->
                <div id="propTypeFilter" class="filter-divs">
                    <button type="button" class="text-icon filter-btn" id="filter-type-btn">Property Type</button>
                    <div class="filter-box raised-box toggleVisible" visible="false">
                        <div class="rowflex">
                            <input type="checkbox" name="pType" value="apartment" id="ptype_apartment">
                            <label for="ptype_apartment">Apartment</label><br>
                        </div>
                        <div class="rowflex">
                            <input type="checkbox" name="pType" value="house" id="ptype_house">
                            <label for="ptype_house">House</label><br>
                        </div>
                        <div class="rowflex">
                            <input type="checkbox" name="pType" value="Floor" id="ptype_floor">
                            <label for="ptype_floor">Floor</label><br>
                        </div>
                    </div>

                </div>

                <!--               MORE FILTERS SECTION-->
                <div id="moreFilters" class="filter-divs">

                    <button type="button" class="text-icon filter-btn" id="filter-more-btn">More Filters</button>

                </div>

            </form>
            <!--                    modal box that contains all the more filters -->
            <div class="modal raised-box" id="more-filters-modal">
                <!--            form just for more filters, it's action is loaded via JS in listprops.js -->
                <form id="more-filters-form" action="" method="get">
                <!--                        header div for more filter box-->
                <div id="more-filters-header" class="afterline">
                    <h1 class="text-midheading">More Filters</h1>
                </div>

                <!--                        body div for more filter box-->
                <div id="more-filters-body" >
                    <!--
                     mfb-divs represent each filter section for example rooms, amenities,rules
                     etc.-->
                    <!-- LYFLY FILTER SECTION INSIDE MORE FILTERS -->
                    <div class="mfb-divs afterline">
                        <!--     multiline-div class contains a small heading with a
                                description underneath and a input on the right side -->
                        <div class="multiline-div">
                            <div>
                                <h2 class="text-icon">Managed by lyfly</h2>
                                <p class="text-small-icon">These properties are managed by the employes of lyfly personally</p>
                            </div>
                            <inputbox type="toggle">
                                <toggle-switch value="lyfly-managed" name="lyfly-managed"></toggle-switch>
                            </inputbox>
                        </div>
                    </div>

                    <!-- ROOMS FILTER SECTIOn INSIDE MORE FILTERS -->
                    <div class="mfb-divs afterline">
                        <div class="mfb-box">
                            <h2 class="text-body font-midheading">Rooms</h2>
                            <!--     single-line-input class contains a description
                            on the left and the input on right-->
                            <div class="single-line-input">
                                <p class="text-icon">Bedrooms</p>
                                <inputbox type="smallnumber">
                                    <button class="circular-btn fontAwesomeBTN"><i class="text-body"> - </i> </button>
                                    <p class="text-icon font-largeheading" >0
                                    </p>
                                    <button class="circular-btn fontAwesomeBTN"><i class="text-body" >+</i> </button>

                                </inputbox>
                            </div>

                            <div class="single-line-input">
                                <p class="text-icon">Bathrooms</p>
                                <inputbox type="smallnumber">
                                    <button class="circular-btn fontAwesomeBTN"><i class="text-body"> - </i> </button>
                                    <input class="text-icon font-largeheading" type="number" value="0" name="nBathrooms">
                                    <button class="circular-btn fontAwesomeBTN"><i class="text-body" >+</i> </button>

                                </inputbox>
                            </div>
                            <div class="single-line-input">
                                <p class="text-icon">Kitchen included</p>
                                <inputbox type="toggle">
                                    <input type="checkbox" name="kitchen" values="kitchen">

                                </inputbox>
                            </div>
                        </div>
                    </div>

                    <!-- AMENITY FILTER SECTION INSIDE MORE FILTERS -->
                    <div class="mfb-divs afterline">
                        <h2 class="text-body font-midheading">Amenities</h2>
                        <div class="gridbox" id="amenities-filter-grid">
                            <div class="checkbox-input">
                                <input class="text-icon" type="checkbox" id="wifi-amenity">
                                <label class="text-icon" for="wifi-amenity">WIFI </i> </label>
                            </div>
                            <div class="checkbox-input">
                                <input class="text-icon" type="checkbox" id="wifi-amenity">
                                <label class="text-icon" for="wifi-amenity">Laundry </i> </label>
                            </div>
                            <div class="checkbox-input">
                                <input class="text-icon" type="checkbox" id="wifi-amenity">
                                <label class="text-icon" for="wifi-amenity">Air Conditioner </i> </label>
                            </div>
                            <div class="checkbox-input">
                                <input class="text-icon" type="checkbox" id="wifi-amenity">
                                <label class="text-icon" for="wifi-amenity">TV </i> </label>
                            </div>
                            <div class="checkbox-input">
                                <input class="text-icon" type="checkbox" id="wifi-amenity">
                                <label class="text-icon" for="wifi-amenity">BreakFast </i> </label>
                            </div>
                            <div class="checkbox-input">
                                <input class="text-icon" type="checkbox" id="wifi-amenity">
                                <label class="text-icon" for="wifi-amenity">Lunch </i> </label>
                            </div>
                            <div class="checkbox-input">
                                <input class="text-icon" type="checkbox" id="wifi-amenity">
                                <label class="text-icon" for="wifi-amenity">Dinner </i> </label>
                            </div>
                        </div>
                    </div>

                    <!-- HOUSE RULES FILTER SECTION INSIDE MORE FILTERS -->
                    <div class="mfb-divs">
                        <h2 class="text-body font-midheading">House Rules</h2>
                        <div class="gridbox" id="rules-filter-grid">
                            <div class="checkbox-input">
                                <input class="text-icon" type="checkbox" id="party-rules">
                                <label class="text-icon" for="wifi-amenity">Party Allowed </i> </label>
                            </div>
                            <div class="checkbox-input">
                                <input class="text-icon" type="checkbox" id="party-rules">
                                <label class="text-icon" for="wifi-amenity">Smoking Allowed </i> </label>
                            </div>
                            <div class="checkbox-input">
                                <input class="text-icon" type="checkbox" id="party-rules">
                                <label class="text-icon" for="wifi-amenity">Pet Friendly </i> </label>
                            </div>

                        </div>
                    </div>

                </div>
                <div id="more-filters-footer" class="beforeline">
                    <div class="filter-submit-btns">
                        <input class="text-icon" type="button" value="Clear">
                        <input class="text-icon" type="submit" id="more-filter-apply"  value="Apply">
                    </div>
                </div>
                </form>
            </div>

        </div>

    <!--    Div showing all properties in a grid-->
        <div id="listprops-grid">

        </div>
    </div>
</div>
<script>
    $(document).ready(function() {

        $("#listprops-grid").on("click",".listprops-item",function(){
            var check1=$(this).find(".img-next").prop("disabled");
            var check2=$(this).find(".img-prev").prop("disabled");

            if(check1==false && check2==false)
                window.location.href = $(this).attr("src");
        });
        $("#listprops-grid").on("click",".add-to-wishlist-btn",function (e) {
            lyfly.setWishlist(e,$(this));
        });

        // // to prevent window to scroll when div is scrolling
        // $( '.show-desc-area' ).on( 'mousewheel DOMMouseScroll', function ( e ) {
        //     var e0 = e.originalEvent,
        //         delta = e0.wheelDelta || -e0.detail;
        //
        //     this.scrollTop += ( delta < 0 ? 1 : -0.2 ) * 7;
        //     e.preventDefault();
        // });

        $(".show-desc-btn").on("click",function (e) {
            var descArea=$(this).siblings(".show-desc-area");
            if(descArea.css("display") == "none") {
                descArea.fadeIn(300);
            }else{
                descArea.fadeOut(300);

            }
            e.stopPropagation();
        });
        $(".img-overlay img[num='1']").addClass("active");

    });
</script>