<?php
$propdata=$this->view_data["data"][0];
$ownerdata=$this->view_data["ownerdata"][0];

?>
<h1 class="prop-title"><?php echo ucfirst($propdata["title"]);?></h1>

<div id="images-box">
    <div class="rowflex rel">
        <div id="first-img" class="imgs nomb"></div>
        <div class="colflex">
            <div class="rowflex">
                <div id="second-img" class="imgs"></div>
                <div id="third-img" class="imgs"></div>
            </div>
            <div class="rowflex">
                <div id="fourth-img" class="imgs nomb"></div>
                <div id="fifth-img" class="imgs nomb"></div>
            </div>
        </div>

    </div>

    <input type="button" id="imgs-showall" value="Show All">
</div>

<div class="rowflex" id="prop-content">


    <div id="left-prop-content">
        <!--            Sharing type heading-->
        <div class="afterline">
            <p class="midsize headprop" id="sharingType">Entire place</p>
            <div class="parasize rowflex" id="roomsInfo">
                <span class="prop-icon">🛏️</span><p>bedrooms: <?php echo $propdata["bedrooms"] ?>  |&nbsp;</p>
                    <span class="prop-icon">🛀</span> <p>bathrooms: <?php echo $propdata["bathrooms"] ?></p>

            </div>
        </div>



        <!--            Description box-->
        <div class="afterline rel" >
            <p class="midsize headprop" >Description</p>
            <p class="parasize" id="propDesc"><?php echo   $propdata["description"] ?>
            </p>
            <div class="rowflex" id="showDesc"><input type="button" value="Continue" onclick="showFull()"></div>
        </div>



        <!--                Amenities and other info box-->
        <div class="rowflex" id="prop-info-box">
            <div id="prop-overview" class="prop-info">
                <div class="afterline"><p class="prop-heading midsize">Overview</p></div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">&#127968;</span>
                    <div>
                        <p class="parasize">Propery Type</p>
                        <p class="smparasize"> Apartment</p>
                    </div>
                </div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">🛏️</span>
                    <div>
                        <p class="parasize">Bedrooms</p>
                        <p class="smparasize"> 1</p>
                    </div>
                </div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">🛀</span>
                    <div>
                        <p class="parasize">Bathrooms</p>
                        <p class="smparasize"> 1</p>
                    </div>
                </div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">&#127859;</span>
                    <div>
                        <p class="parasize">Kitchen</p>
                        <p class="smparasize"> Yes</p>
                    </div>
                </div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">&#128467;</span>
                    <div>
                        <p class="parasize">Agreement Period</p>
                        <p class="smparasize"> 1 year</p>
                    </div>
                </div>

            </div>
            <div id="prop-rules" class="prop-info">
                <div class="afterline"><p class="prop-heading midsize">Unit</p></div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">&#127968;</span>
                    <div>
                        <p class="parasize">Pet Friendly</p>
                        <p class="smparasize"> No</p>
                    </div>
                </div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">🛏️</span>
                    <div>
                        <p class="parasize">Parties Allowed</p>
                        <p class="smparasize"> Yes</p>
                    </div>
                </div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">🛀</span>
                    <div>
                        <p class="parasize">Smoking allowed</p>
                        <p class="smparasize"> No</p>
                    </div>
                </div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">&#127859;</span>
                    <div>
                        <p class="parasize">Air Conditioner</p>
                        <p class="smparasize"> Yes</p>
                    </div>
                </div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">&#128467;</span>
                    <div>
                        <p class="parasize">WIFI</p>
                        <p class="smparasize"> Yes</p>
                    </div>
                </div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">&#128467;</span>
                    <div>
                        <p class="parasize">TV</p>
                        <p class="smparasize"> Yes</p>
                    </div>
                </div>
            </div>
            <div id="prop-amenities" class="prop-info">
                <div class="afterline"><p class="prop-heading midsize">Building</p></div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">&#127968;</span>
                    <div>
                        <p class="parasize">Propery Type</p>
                        <p class="smparasize"> Apartment</p>
                    </div>
                </div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">🛏️</span>
                    <div>
                        <p class="parasize">Bedrooms</p>
                        <p class="smparasize"> 1</p>
                    </div>
                </div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">🛀</span>
                    <div>
                        <p class="parasize">Bathrooms</p>
                        <p class="smparasize"> 1</p>
                    </div>
                </div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">&#127859;</span>
                    <div>
                        <p class="parasize">Kitchen</p>
                        <p class="smparasize"> Yes</p>
                    </div>
                </div>
                <div class="prop-unit rowflex">
                    <span class="prop-icon">&#128467;</span>
                    <div>
                        <p class="parasize">Agreement Period</p>
                        <p class="smparasize"> 1 year</p>
                    </div>
                </div>

            </div>
        </div>
    </div>



    <div id="right-prop-content">
        <div id="address-box"><div id="map"></div><p><?php
                echo getProperAddress($propdata["address"],$propdata["city"],$propdata["state"]) ?></p></div>
        <div id="contact-box">
           <p> <?php echo $ownerdata["first_name"]." ".$ownerdata["last_name"]?>
            <br>
            <?php echo $ownerdata["phone_num"]?>
            <br>
            <?php echo $ownerdata["email"]?>
           </p>

        </div>
    </div>

</div>





<!--Map Loading Scripts-->
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&key=AIzaSyDTWvYehAfHTElUe6NyRq0KVAuZVoI4RQM&ver=3.exp"></script>
<script>

    displayMap();
    function initMap(latitude,longitude) {

        var uluru = {lat: latitude, lng: longitude};

        var map = new google.maps.Map(
            document.getElementById('map'), {zoom: 18,
                center: uluru});
        // The marker, positioned at Uluru
        var marker = new google.maps.Marker({position: uluru,
            draggable:true,
            animation:google.maps.Animation.DROP,
            map: map});
    }

    function displayMap(){
        var geocoder = new google.maps.Geocoder();
//        address to be changed later
        var address = "<?php
            echo getProperAddress($propdata["address"],$propdata["city"],$propdata["state"]);
            ?>";
        geocoder.geocode( { 'address': address}, function(results, status) {

            if (status == google.maps.GeocoderStatus.OK) {
                var latitude = results[0].geometry.location.lat();
                var longitude = results[0].geometry.location.lng();


                initMap(latitude,longitude);

            }
        });
    }

</script>


<!--Styling Scripts-->
<script>
    //Sticky Contact Info
    $(document).ready(function(){
        if($("#propDesc")[0].clientHeight < $("#propDesc")[0].scrollHeight){

        }else{
            $("#showDesc").css("display","none");

        }
        var contactTop=$("#contact-box").offset().top;
        $(window).scroll(function(){
            var windowTop =$(window).scrollTop();
            if(windowTop+10>=contactTop){
                $("#contact-box").addClass("sticky");
                $("#contact-box").width($("#right-prop-content").width());
            }else{
                $("#contact-box").removeClass("sticky");
                $("#contact-box").width("100%");

            }
        })});

    function showFull(){
        $("#propDesc").css("height","auto");
        $("#showDesc").css("display","none");
    }
</script>
