<div id="host-box">
    <form id="hb-input-box" action="/host/setup">
        <h1>Earn money by hosting  </h1>
        <h4>Tell us a little about your place</h4>

        <input class="hb-inputs" placeholder="Location" id="host-place" type="text">
        <div class="horizontal-inputs">
            <input class="hb-inputs" placeholder="Type" id="host-type" type="text">
            <input class="hb-inputs" placeholder="# of rooms" id="host-num" type="text">
        </div>
        <input value="Get Started" type=submit >
    </form>
</div>
<div id="host-benefits" class="rowflex">
    <div id="hb-why" class="hb-reasons">
        <h1>Why host on Lyfly?</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ornare purus nulla, nec egestas lacus semper eget. Vestibulum tristique, ligula sit amet porttitor interdum, urna lectus condimentum orci, at commodo est ipsum et velit</p>
    </div>
    <div id="hb-back" class="hb-reasons">
        <h1>Why host on Lyfly?</h1>
        <p>. Sed ut efficitur nunc. Maecenas vel felis nec lectus dapibus pretium. Duis odio lectus, egestas id tellus ut, scelerisque posuere diam. Mauris sed diam commodo lectus lobortis lacinia</p>
    </div>
</div>
<div id="host-explain" class="rowflex">
    <div id="he-heading"><h1>Hosting </h1>
        <h1>in</h1>
        <h1>3 </h1>
        <h1>ez </h1>
        <h1>steps</h1>

    </div>
    <div id="he-steps" >
        <ul class="notypelist">
            <li>

                <div><img src="/imgs/tick.png"><span>Why host on Lyfly?</span></div>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ornare purus nulla, nec egestas lacus semper eget. Vestibulum tristique, ligula</p>
            </li>
            <li>
                <div><img src="/imgs/tick.png"><span>Why host on Lyfly?</span></div>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ornare purus nulla, nec egestas lacus semper eget. Vestibulum tristique, ligula</p>
            </li>
            <li>
                <div><img src="/imgs/tick.png"><span>Why host on Lyfly?</span></div>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ornare purus nulla, nec egestas lacus semper eget. Vestibulum tristique, ligula</p>
            </li>
        </ul>
    </div>
</div>
<!--    \2714-->
<div id="host-priority">
    <p class="heading headline">Safety is our priority</p>
    <div id="hp-box" class="rowflex">
        <div id="hpb-left"><p class="parasize">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ornare purus nulla, nec egestas lacus semper eget. Vestibulum tristique, ligulaLorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ornare purus nulla, nec egestas lacus semper eget. Vestibulum tristique, ligulaonsectetur adipiscinonsectetur adipiscin</p></div>
        <div id="hpb-right">
            <ul class="parasize notypelist">
                <li>Lorem ipsum dolor sit amet, consectetur </li>
                <li>Lorem ipsum dolor sit amet, consectetur </li>
                <li>Lorem ipsum dolor sit amet, consectetur </li>
                <li>Lorem ipsum dolor sit amet, consectetur </li>
                <li>Lorem ipsum dolor sit amet, consectetur </li>
                <li>Lorem ipsum dolor sit amet, consectetur </li>

                <li>Lorem ipsum dolor sit amet, consectetur </li>

            </ul>
        </div>

    </div>
</div>

<div id="host-reviews">
    <div id="hr-first" class="rowflex">
        <div id="hrf-text" class="midsize">
            <p>Helped me earn extra money for my son's tuition</p>
        </div>
        <div id="hrf-img">
            <img src="/imgs/avatarperson.jpg" alt="Avatar">
        </div>
    </div>
</div>

<div id="host-about">
    <p class="heading headline">About Lyfly</p>
    <div id="ha-box" class="rowflex">
        <div id="ha-about" class="parasize">
            <p class="midsize">Why host on Lyfly?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ornare purus nulla, nec egestas lacus semper eget. Vestibulum tristique, ligula sit amet porttitor interdum, urna lectus condimentum orci, at commodo est ipsum et velit</p>
        </div>
        <div id="ha-why" class="parasize">
            <p class="midsize">Why host on Lyfly?</p>
            <p>. Sed ut efficitur nunc. Maecenas vel felis nec lectus dapibus pretium. Duis odio lectus, egestas id tellus ut, scelerisque posuere diam. Mauris sed diam commodo lectus lobortis lacinia</p>
        </div>

    </div>
</div>

<script>

    $("#hb-input-box").submit(function(e){
        if(!login_params.signed){
            openLogin();
            e.preventDefault();
        }
    });
</script>
