<div id="host-box">
    <form id="hb-input-box" action="/host/unfinished">
        <h1 class="text-largeheading">Earn money by hosting  </h1>
        <h4 class="text-body">Tell us a little about your place</h4>

        <input class="text-small-body" placeholder="Location" id="host-place" type="text">
        <div class="horizontal-inputs">
            <input class="text-small-body" placeholder="Type" id="host-type" type="text">
            <input class="text-small-body" placeholder="# of rooms" id="host-num" type="text">
        </div>
        <button type="submit" class="text-small-body">Get Started </button>
    </form>
</div>
<div id="host-works" class="afterline">
<h1 class="text-largeheading"> How hosting works</h1>
    <div class="rowflex">
        <div class="hw-card leftmost">
            <img src="/imgs/img_avatar2.png">
            <h2 class="text-midheading">Choose your requirements</h2>
            <p class="text-icon">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda debitis distinctio perspiciatis tenetur voluptatem? Debitis iure, vero. Aliquam est eum unde voluptatibus. Animi cum earum eligendi facere incidunt ipsa, nisi?</p>
        </div>
        <div class="hw-card leftmost">
            <img src="/imgs/img_avatar2.png">

            <h2 class="text-midheading">Choose your requirements</h2>
            <p class="text-icon">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda debitis distinctio perspiciatis tenetur voluptatem? Debitis iure, vero. Aliquam est eum unde voluptatibus. Animi cum earum eligendi facere incidunt ipsa, nisi?</p>
        </div><div class="hw-card leftmost">
            <img src="/imgs/img_avatar2.png">
            <h2 class="text-midheading">Choose your requirements</h2>
            <p class="text-icon">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda debitis distinctio perspiciatis tenetur voluptatem? Debitis iure, vero. Aliquam est eum unde voluptatibus. Animi cum earum eligendi facere incidunt ipsa, nisi?</p>
        </div><div class="hw-card leftmost">
            <img src="/imgs/img_avatar2.png">
            <h2 class="text-midheading">Choose your requirements</h2>
            <p class="text-icon">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda debitis distinctio perspiciatis tenetur voluptatem? Debitis iure, vero. Aliquam est eum unde voluptatibus. Animi cum earum eligendi facere incidunt ipsa, nisi?</p>
        </div>


    </div>
</div>


<div id="host-community" class="afterline">
    <div id="hc-scroller"

         class="rowflex hidescrollbar">

        <div class="hc-card leftmost">
            <img src="/imgs/avatarperson.jpg">
            <h2 class="text-midheading">Darrel</h2>
            <p class="text-icon">Four properties in Chandigarh</p>
        </div>
        <div class="hc-card">
            <img src="/imgs/avatarperson.jpg">
            <h2 class="text-midheading">Darrel</h2>
            <p class="text-icon">Four properties in Chandigarh</p>
        </div>
        <div class="hc-card"
           >
            <img src="/imgs/avatarperson.jpg">
            <h2 class="text-midheading">Darrel</h2>
            <p class="text-icon">Four properties in Chandigarh</p>
        </div>
        <div class="hc-card rightmost">
            <img src="/imgs/avatarperson.jpg">
            <h2 class="text-midheading">Darrel</h2>
            <p class="text-icon">Four properties in Chandigarh</p>
        </div>
    </div>
    <div id="hc-info">
        <div class="fade-gradient"></div>
        <div>
        <h1 class="text-largeheading"> Join a vibrant host community</h1>
        <p class="text-icon">Create memorable experiences for travellers and earn money to pursue the things you love.</p>
        <button class="text-body">Get Started</button>
        </div>
    </div>

</div>

<div id="hc-help" class="rowflex">
    <div class="l" data-aos="fade-right" data-aos-anchor-placement="center-bottom"><h1 class="text-largeheading">We are here to help!</h1> </div>
    <div class="r text-body">
        <div class="hch-features"
             data-aos="fade"
             data-aos-duration="1500">
            <p class="bold-font text-midheading"><i class="fa fa-headphones"></i>Hey there </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, quaerat!</p>
        </div>
        <div class="hch-features"
             data-aos="fade"
             data-aos-duration="1500">
            <p class="bold-font text-midheading"><i class="fa fa-headphones"></i>Hey there </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, quaerat!</p>
        </div>
        <div class="hch-features"
             data-aos="fade"
             data-aos-duration="1500">
            <p class="bold-font text-midheading"><i class="fa fa-headphones"></i>Hey there </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, quaerat!</p>
        </div>
        <div class="hch-features"
             data-aos="fade"
             data-aos-duration="1500">
            <p class="bold-font text-midheading"><i class="fa fa-headphones"></i>Hey there </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, quaerat!</p>
        </div>
    </div>
</div>

<script>

    AOS.init({once:true});
    $(document).ready(function() {
        $("#hb-input-box").submit(function (e) {
            if (!login_params.signed) {
                openLogin();
                e.preventDefault();
            }
        });
    });
</script>
