<?php

$unfinished=$this->getViewDataParam("properties");
$indexes=$this->getViewDataParam("indexes");
?>


<div class="half-window">
    <div class="page-heading"><h1 class="text-midheading">Unfinished Properties</h1> </div>
    <?php foreach ($unfinished as $up): ?>
<form class="unfinshed-prop rel colflex" action="/host/setup/<?php echo $indexes[$up["id"]]?>" method="post" >
    <div class="rowflex">
        <div class="up-title text-midheading"><?php echo $up["title"] ?></div>
        <div class="up-delete" "><button type="button" class="up-delete-btn text-icon" for="<?php echo $indexes[$up["id"]]?>">Delete</button></div>
    </div>
    <div class="rowflex bottom-div text-midheading">
        <div class="up-date"><p>Date Created : <?php echo $up["dateAdded"] ?></p></div>
        <div class="up-complete"><p>42%</p></div>
    </div>

</form>
    <?php endforeach; ?>

</div>

<script>
    $(document).ready(function (){
       $(".unfinshed-prop").on("click",function(){
           $(this).submit();
       })
        $(".up-delete-btn").on("click",function (e){
            e.stopPropagation();
            alert("dsa");
            let url="/host/delete_unfinished/"+$(this).attr("for");
            location.assign(url);
        });

    });
</script>
