<?php

$unfinished=$this->getViewDataParam("properties");
$indexes=$this->getViewDataParam("indexes");
?>


<div class="half-window">
    <div class="page-heading"><h1 class="text-midheading">Unfinished Properties</h1> </div>
    <?php foreach ($unfinished as $up): ?>
<form class="unfinshed-prop rel colflex" action="/host/setup" method="get">
    <div class="rowflex">
        <div class="up-title text-midheading">Hey</div>
        <div class="up-delete"><button class="text-icon">Delete</button></div>
    </div>
    <div class="rowflex bottom-div text-midheading">
        <div class="up-date"><p>Date Created : 24 march 2021</p></div>
        <div class="up-complete"><p>42%</p></div>
    </div>
    <input type="hidden" name="prop" value="<?php echo $indexes[$up["id"]]?>">

</form>
    <?php endforeach; ?>

</div>

<script>
    $(document).ready(function (){
       $(".unfinshed-prop").on("click",function(){
           $(this).submit();
       })
    });
</script>
