<?php
$approved_properties=$this->view_data["approved_props"];
$unapproved_properties=$this->view_data["unapproved_props"];

$this->convert_php_to_jsvars([$approved_properties,$unapproved_properties],
    ["approved_props","unapproved_props"]);
?>



<div id="listprops-grid">

</div>
<script src="/js/loadprops.js"></script>
<script src="/js/imageslider.js"></script>
<script>
        $(document).ready(function () {
            propsConfig("#listprops-grid","#single-listing",".listprops-item", php_vars.approved_props).loadProps();

        });

</script>
