<?php
$approved_properties=$this->view_data["approved_props"];
$unapproved_properties=$this->view_data["unapproved_props"];

var_dump($approved_properties);
$this->convert_php_to_jsvars([$approved_properties,$unapproved_properties],
    ["approved_props","unapproved_props"]);
?>

<script>
    console.log(php_vars.approved_props);
</script>


<div id="listprops-grid">

</div>

<script>
    $(document).ready(function() {
        console.log("Read");
        propsConfig("#listprops-grid","#single-listing",".listprops-item", php_vars.approved_props).loadProps();

        $(".listprops-item").click(function () {
                window.location.href=$(this).attr("src");
            }
        );
    });
</script>