<!DOCTYPE html>
<html>
<head>
    <title>Admin Login</title>
    <script src="/js/jquery-3.5.1.js"></script>
</head>
<body>

<form id="getuser" action="/admin/loginUser" method="post">
    <input type="text" placeholder="Username" name="admin_username" id="admin_username">
    <input type="password" placeholder="Password" name="admin_password" id="admin_password">

    <input type="submit" value="Submit">
</form>
</body>
<script>

</script>
</html>